on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Check files
        id: hello
        uses: anpato/ld_action@v1.1
        with:
          target_dir: "packages/ld"
      # Use the output from the `hello` step
